[package]
edition = "2021"
name = "random_metro_network"
version = "0.1.0"
[dependencies]
fastrand = "*"
gnuplot = "*"
ndarray = "*"
serde_yaml = "*"
structopt = "*"

[dependencies.serde]
features = ["derive"]
version = "1.0"
