[package]
edition = "2021"
name = "random_metro_network"
version = "0.1.0"
[dependencies]
gnuplot = "*"
ndarray = "*"
serde_yaml = "*"
structopt = "*"
rand = "0.8.4"
rand_distr = "0.4.2"

[dependencies.serde]
features = ["derive"]
version = "1.0"
